<?php
namespace app\common\command;

use think\console\Command;
use think\console\Input;
use think\console\Output;

class Run extends Command
{
    protected function configure()
    {
        $this->setName('run')->setDescription('built-in server ');
    }

    protected function execute(Input $input, Output $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
