<?php
return [
    'theme' => [
            'list' => [
                    0 => [
                            'id' => 1,
                            'title' => '清凉一夏，折扣季',
                            'description' => '秋天是金色的。麦穗是金色的，秋阳是金色的。虽然冬快至，但宜人的温度总是让我们心情愉快#我们为您精选了一系列秋冬折扣商品，慢慢挑选吧~',
                            'name' => 't-1',
                            'entrance_img' => 'http://i2.sleeve.7yue.pro/m2.png',
                            'extend' => NULL,
                            'internal_top_img' => 'http://i2.sleeve.7yue.pro/m33.png',
                            'title_img' => '',
                            'tpl_name' => 'janna',
                            'online' => true,
                        ],
                    1 => [
                            'id' => 4,
                            'title' => '每周上新',
                            'description' => '风袖`每周上新`活动#每周都有一款折扣商品，每周都有适合你的唯一专属#有Ins复古风装饰；金属CD唱片夹；每周来逛逛，找到你所喜爱的东西',
                            'name' => 't-2',
                            'entrance_img' => NULL,
                            'extend' => NULL,
                            'internal_top_img' => 'http://i2.sleeve.7yue.pro/m1.png',
                            'title_img' => 'http://i2.sleeve.7yue.pro/m3.png',
                            'tpl_name' => NULL,
                            'online' => true,
                        ],
                    2 => [
                            'id' => 5,
                            'title' => '风袖甄选',
                            'description' => '甄选',
                            'name' => 't-3',
                            'entrance_img' => 'http://i2.sleeve.7yue.pro/m9.png',
                            'extend' => NULL,
                            'internal_top_img' => 'http://i2.sleeve.7yue.pro/m11.png',
                            'title_img' => '',
                            'tpl_name' => 'diana',
                            'online' => true,
                        ],
                    3 => [
                            'id' => 6,
                            'title' => '时尚穿搭',
                            'description' => '帅点才有女朋友',
                            'name' => 't-4',
                            'entrance_img' => 'http://i2.sleeve.7yue.pro/m10.png',
                            'extend' => NULL,
                            'internal_top_img' => 'http://i2.sleeve.7yue.pro/m12.png',
                            'title_img' => '',
                            'tpl_name' => 'irelia',
                            'online' => true,
                        ],
            ],
            'one' => [
                'id' => 6,
                'title' => '时尚穿搭',
                'description' => '帅点才有女朋友',
                'name' => 't-4',
                'extend' => NULL,
                'entrance_img' => 'http://i2.sleeve.7yue.pro/m10.png',
                'internal_top_img' => 'http://i2.sleeve.7yue.pro/m12.png',
                'online' => true,
                'title_img' => NULL,
                'tpl_name' => 'irelia',
                'spu_list' => [
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                    [
                        'id' => 2,
                        'title' => 'Sleeve羊绒毛衣',
                        'subtitle' => 'Sleeve风袖说当季经典款',
                        'category_id' => 17,
                        'root_category_id' => 3,
                        'price' => '77.00',
                        'img' => 'http://i2.sleeve.7yue.pro/m26.png',
                        'for_theme_img' => '',
                        'description' => null,
                        'discount_price' => '62.00',
                        'tags' => '包邮$热门',
                        'is_test' => true,
                        'online' => true,
                    ],
                ],
            ],
    ],
    'banner' => [
            0 => [
                    'id' => 1,
                    'name' => 'b-1',
                    'description' => '首页顶部主banner',
                    'img' => NULL,
                    'title' => NULL,
                    'items' => [
                            0 => [
                                    'id' => 12,
                                    'img' => 'http://i2.sleeve.7yue.pro/m1.png',
                                    'keyword' => 't-2',
                                    'type' => 3,
                                    'name' => NULL,
                                    'banner_id' => 1,
                            ],
                            1 => [
                                    'id' => 13,
                                    'img' => 'http://i1.sleeve.7yue.pro/assets/702f2ce9-5729-4aa4-aeb3-921513327747.png',
                                    'keyword' => '23',
                                    'type' => 1,
                                    'name' => NULL,
                                    'banner_id' => 1,
                            ],
                            2 => [
                                    'id' => 14,
                                    'img' => 'http://i1.sleeve.7yue.pro/assets/b8e510a1-8340-43c2-a4b0-0e56a40256f9.png',
                                    'keyword' => '24',
                                    'type' => 1,
                                    'name' => NULL,
                                    'banner_id' => 1,
                            ],
                        ],
            ],
    ],
    'activity' => [
            0 => [
                    'id' => 1,
                    'title' => '全场无门槛立减券',
                    'entrance_img' => 'http://i2.sleeve.7yue.pro/m14.png',
                    'online' => true,
                    'remark' => '全场无门槛立减',
                    'start_time' => NULL,
                    'end_time' => NULL,
            ],
            1 => [
                'id' => 2,
                'title' => '夏日好礼送不停',
                'entrance_img' => 'http://i2.sleeve.7yue.pro/m14.png',
                'online' => true,
                'remark' => '限服装、鞋、文具等商品',
                'start_time' => NULL,
                'end_time' => NULL,
                "coupons" => [
                    [
                        "id" => 3,
                        "title" => "无门槛减0.1券",
                        "start_time" => 1564956702000,
                        "end_time" => 1943647908000,
                        "description" => null,
                        "full_money" => null,
                        "minus" => '0.1',
                        "rate" => null,
                        "type" => 3,
                        "remark" => "全场无门槛立减",
                        "whole_store" => true
                    ]
                ],
            ],
    ],
    'category' => [
            0 => [
                    'id' => 1,
                    'title' => '服装',
                    'img' => 'http://i1.sleeve.7yue.pro/grid/clothing.png',
                    'name' => NULL,
                    'category_id' => NULL,
                    'root_category_id' => 2,
            ],
            1 => [
                    'id' => 2,
                    'title' => '包包',
                    'img' => 'http://i1.sleeve.7yue.pro/grid/bag.png',
                    'name' => NULL,
                    'category_id' => NULL,
                    'root_category_id' => 3,
            ],
            2 => [
                    'id' => 3,
                    'title' => '鞋',
                    'img' => 'http://i1.sleeve.7yue.pro/grid/shoes.png',
                    'name' => NULL,
                    'category_id' => NULL,
                    'root_category_id' => 1,
            ],
            3 => [
                    'id' => 4,
                    'title' => '饰品',
                    'img' => 'http://i1.sleeve.7yue.pro/grid/jewelry.png',
                    'name' => NULL,
                    'category_id' => NULL,
                    'root_category_id' => 5,
            ],
            4 => [
                    'id' => 5,
                    'title' => '居家',
                    'img' => 'http://i1.sleeve.7yue.pro/grid/furniture.png',
                    'name' => NULL,
                    'category_id' => NULL,
                    'root_category_id' => 4,
            ],
            5 => [
                    'id' => 6,
                    'title' => '工艺',
                    'img' => 'http://i1.sleeve.7yue.pro/grid/book.png',
                    'name' => NULL,
                    'category_id' => NULL,
                    'root_category_id' => 24,
            ],
    ],
    'coupon' => [
      [
          'id' => 3,
          'title' => '无门槛减0.1券',
          'start_time' => 1564956702000,
          'end_time' => 1943647908000,
          'description' => null,
          'full_money' => null,
          'minus' => 0.10,
          'rate' => null,
          'type' => 3,
          'remark' => '全场无门槛立减',
          'whole_store' => true,
      ],
    ],
];
